import type { Metadata } from "next";
import "@/styles/global.css";
import FontInter from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const defaultFont = FontInter;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={defaultFont.className}>
        {children}
      </body>
    </html>
  );
}
